name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize    
    branches:
      - main

jobs:
  pull_request_job:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Debug
      run: |
        ls -la /home/runner/work/

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: |
        test_output=$(npm test)
        # Check if the output contains a specific string or pattern
        if [[ ! $test_output == *"failed"* ]]; then
          echo "Tests passed successfully"
        else
          echo "Tests failed or produced unexpected output"
          exit 1
        fi