name: Merge Grp

on:
  merge_group:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install

    - name: Sleep 10 before
      run: |
            sleep 10
    - name: Use GitHub Token
      run: |
        echo "Either My GitHub Token is ${{ secrets.GH_TOKEN }}"
        echo "Or My GitHub Token is ${{ secrets.GITHUB_TOKEN }}"
    - name: touch and add file
      run: |
        chmod +x increment_version.sh
        ./increment_version.sh
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}